version: "3"

networks:
  kong-net:

services:
  kong-database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - 5432:5432

  kong-database-migration:
    image: kong:2.8.1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
    command: ["kong", "migrations", "bootstrap"]
    depends_on:
      - kong-database

  kong-gateway:
    image: kong:2.8.1-alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 ssl
      # use self-signed cert
      - KONG_SSL_CERT=/certificate/cert.pem
      - KONG_SSL_CERT_KEY=/certificate/key.pem
      - KONG_ADMIN_SSL_CERT=/certificate/cert.pem
      - KONG_ADMIN_SSL_CERT_KEY=/certificate/key.pem
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./certificate:/certificate
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    restart: always
    depends_on:
      - kong-database

  kong-gui:
    image: pantsel/konga
    environment:
      - TOKEN_SECRET=12345
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kongpass
      - DB_DATABASE=kong
      # ignore self-signed cert error
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 1337:1337
    restart: always
    depends_on:
      - kong-database
